TritonDataCenter/smartos-live

README.md, configure
Took the opportunity here to re-organize the readme a bit more sensibly.
=> OS-8010 move platform repositories out of Gerrit

src/lib/sdc/network.sh
This is an updated PR based on the following closed PR:
https://github.com/joyent/smartos-live/pull/782
I have found the updated file and changed the max MTU to 65536.
=> Bump Maximum MTU to 65535

src/vm/node_modules/vmload/index.js, src/vm/package.json
All tests are passing after this change:
```
#
#
```
=> OS-8057 vminfod should round refreservation values

src/vm/man/vmadm.1m.md, src/vm/node_modules/VM.js, src/vm/node_modules/proptable.js
The smarts-live portions necessary for the change.
=> OS-8136 Add DISCARD/TRIM support to bhyve

src/vm/man/vmadm.1m.md, src/vm/node_modules/proptable.js
Counter part for joyent/illumos-joyent#287 as this needs changes in both locations, progress and motivation tracked in the other PR
=> OS-8158 Support NVMe as device model for bhyve

man/usr/share/man/man1m/piadm.1m.md, src/piadm.sh
OS-8208 piadm man page formatting errors
=> OS-8207 piadm "BOOT BITS?" header is confusing

man/usr/share/man/man1m/piadm.1m.md, src/piadm.sh
Stubs, and the ability to detect a Triton CN.  Do not use yet save to test "yes I'm on a CN" vs. "No I'm not on a CN".
=> OS-8206 Enable piadm(1M) to detect and install on-disk iPXE on Triton CNs

src/lib/sdc/usb-key.sh, src/piadm.sh
Eventually I'll file a TRITON bug to catch all of the various repos commits.  Meanwhile, there's an `rfd176` branch in each repo that is affected by Phase 3.
=> RFD176 branch

src/node_modules/zfs.js
This includes changes from node-zfs for the following:
* CNAPI-286
* AGENT-645
* AGENT-785
* TOOLS-607
=> TRITON-2242 zfs.js needs to be reconciled across smartos-live, node-zfs and node-zfs/linuxcn

src/piadm.sh
=> OS-8354 piadm should only run in the global zone, and mostly as root

src/piadm.sh
=> OS-8353 piadm should get the download location from a config file

Makefile
Still under build, but should be VERY similar to OS-8250
=> OS-8363 Create 8gb image in smartos-live

src/node_modules/zfs.js
=> Fix setup of encrypted zpool when setting up a new compute node

Jenkinsfile
Org webhooks are also in place now so once this is created, jira should automatically get the PR link, and once it's merged Jenkins should auto build it.
=> TOOLS-2541 Update slack channel

README.md
Updates README.md to show `git` rather than `scmgit`.
=> OS-8382 Update README.md

Jenkinsfile
WIP, thinking that parallel stage builds (which can be done as they're all self-contained) might be a new parameter for build-with-parameters.
=> OS-8405 Have Jenkinsfile use parallel stages

Makefile, README.md, tools/preflight
Companion to TritonDataCenter/illumos-extra#83.
=> OS-8412 Bump OpenSSH to 9.1p1

Jenkinsfile, Makefile, tools/build_jenkins
Not intended for 20221117, but time to take a look.
=> OS-8422 Give gcc10 (alternate-compiler) its own directory in .../public/builds/.

tools/build_illumos
Derives (once) BANNER_YEAR for the environment where TritonDataCenter/illumos-joyent#429 can exploit it.
=> OS-8433 Welcome 2023

Jenkinsfile, configure
Would like this at least running in-branch on Jenkins before upstream makes its cut-over, and depending on how the branch goes, we MAY wish to make the switch before upstream does.
=> OS-8327 Switch default compiler to gcc10 for SmartOS

src/smartdc/lib/ntp_config.js
Companion: TritonDataCenter/illumos-joyent#453
=> OS-8484 Headnode NTP config should be able to support RAN networks

README.md, default.configure-build, docs/dev-upgrade.md, src/piadm.sh, src/vm/runtest, tools/build_strap, tools/smartos-index, tools/smartos-release
This depends on TritonDataCenter/eng#67.
=> TOOLS-2574 Purge dependency on us-east.manta.joyent.com name

tools/mancf/main.c
This PR substantially reworks the previous somewhat incomplete ordering engine.  It performs a crude [topological sort](https://en.wikipedia.org/wiki/Topological_sorting), using something that resembles the depth-first search algorithm if you keep the lighting turned low.
It sorts the list in the way that I think makes the most sense, given the section number rejiggery:
```
#
#
#
MANSECTS=1,1c,8,1b,2,3,3c,3avl,3bsm,3c_db,3cfgadm,3commputil,3contract,3cpc,3curses,3dat,3devid,3devinfo,3dlpi,3dns_sd,3elf,3exacct,3ext,3fcoe,3fstyp,3gen,3gss,3jedec,3kstat,3kvm,3ldap,3lgrp,3lib,3m,3mail,3malloc,3mp,3mpapi,3mvec,3nsl,3nvpair,3ofmt,3pam,3papi,3picl,3picltree,3pool,3proc,3project,3resolv,3rpc,3rsm,3sasl,3scf,3sec,3secdb,3sip,3socket,3head,3stmf,3sysevent,3tecla,3utempter,3uuid,3vnd,3volmgt,3x11,3xa …
```
=> OS-8436 improve man.cf sorting

man/usr/share/man/man8/piadm.8.md, src/piadm.sh
Portions-contributed-by: Jason King <jason.brian.king+illumos@gmail.com>
Replacement of #1080 .
=> OS-8498 Want 'piadm destroy' as an alias for 'piadm remove'

Jenkinsfile
=> OS-8584 Introduce gcc14 as the shadow-compiler

src/smartdc/lib/smartos_prompt_config.sh
https://smartos.org/bugview/OS-8637
=> OS-8637: Want improved swap/dump volume configuration

tools/build_changelog
=> OS-8656 build_changelog should stop using GNU grep

man/manifest, man/usr/share/man/man7/joyent.7
=> OS-8646 Man page presence for joyent-minimal(7) and builder(7)
