configure
Tested by running ./configure on my standard 80x24 terminal window.
=> OS-8051 OS-8032 blocks ./configure if git output is too big

src/fw/package.json, src/fw/test/integration/examples.test.js, src/fw/test/integration/in-zone-enabled.test.js, src/fw/test/integration/ipsec.test.js, src/fw/test/lib/fw.js
Both of these test files:
- test/integration/examples.test.js
- test/integration/ipsec.test.js
pass after this change.
I tweaked the `statsContain()` function to allow the wanted rule to be a prefix of the vm rules (it actually was the other way around before this - the vm rule was a prefix of the wanted rule), which then ignores the set-tag() part of the rule.
=> OS-8061 test fw "vmadm - stats after vmadm_vm1" failure

tools/build_jenkins, tools/smartos-release
A demo of this directory structure, along with corresponding (tweaked to look at ~timf rather than ~Joyent_Dev) smartos-changelog changes from joyent/smartos-change.log#8 is at https://us-east.manta.joyent.com/timf/public/SmartOS/smartos.html with just a single dummy release in /timf/public/SmartOS/20200103T004546Z
The `*-latest*.*` artifacts are not in /timf/public/SmartOS as I created that demo when running the smartos-release script from a workspace that hadn't done a full build.
=> OS-8068 update the smartos release process to no longer use snaplinks

src/vm/man/vmadm.1m.md, src/vm/node_modules/VM.js, src/vm/node_modules/expander.js, src/vm/node_modules/proptable.js, src/vm/tests/test-update.js
This PR replaces #863
Original work done by @jclulow, man page update + tests done by @sjorge 
```
[root@00-0c-29-51-55-da /usr/vm/test]# ./runtest tests/test-update.js
Already have "imgapi" image source "https://images.joyent.com", no change
Already have "docker" image source "https://docker.io", no change
TAP version 13
ok 1 created VM: 7b64f9ad-f4f7-466f-9046-bca2923a6d95
ok 2 failed to set ips, was ["10.254.254.254/24"], expected ["10.254.254.254/24"]
ok 3 failed to set netmask, was "255.255.255.0", expected "255.255.255.0"
ok 4 failed to set nic_tag, was "external", expected "external"
ok 5 failed to set vlan_id, was 0, expected 0
ok 6 failed to set gateways, was ["10.254.254.1"], expected ["10.254.254.1"]
ok 7 failed to set mac, was "01:02:03:04:05:06", expected "01:02:03:04:05:06" …
```
=> OS-7317 vmadm "remove_filesystems" is both broken and undocumented

tools/build_boot_image
Some memory cards such as the Kingston 2GB SDCard that ships in Dell servers have fewer than 2GB of space for writing the SmartOS boot image. I have lowered the image size by 60MB to accommodate cards that fall short.
I have made minimal changes so as to avoid touching the "proforma" workflow or options and have tested building and running from this image on aforementioned cards.
Discussion here: https://smartos.topicbox.com/groups/smartos-discuss/Tecbe189dfeb6ebfc/the-partition-size-is-fixed-1-86g-in-usb-stick-can-it-be-enlarged
=> OS-8170 size SmartOS USB for smaller cards

src/vm/node_modules/VM.js, src/vm/tests/test-snapshots.js
Adds a second condition to ignore when attempting to umount a snapshot before deleting it (directory does not exist).
The subsequent step already ignores a failed delete of the missing directory.
Adds a testcase to validate this scenario.
Improves test output when creating/deleting snapshots.
Fixes joyent/smartos-live#943, fixes joyent/smartos-live#480.
Output from new "nomountdir" testcase as executed on smartos 20200326T183047Z:
```
ok 415 creating snapshot nomountdir of 018f9c08-267c-cecb-d8b2-f10f50bca46a: success
ok 416 loading VM after create
ok 417 1 snapshot(s) after create: [expected: 1]
ok 418 created snapshot for nomountdir test: success
ok 419 umount-ed /zones/018f9c08-267c-cecb-d8b2-f10f50bca46a/root/checkpoints/nomountdir: success
ok 420 deleted …
```
=>  ignore missing mountpoint when deleting snapshots

.gitignore, man/Makefile, man/manifest, man/usr/share/man/man1m/piadm.1m.md, src/Makefile, src/lib/sdc/usb-key.sh, src/manifest, src/mkzpool.js, src/node_modules/zfs.js, src/piadm.sh, src/smartdc/lib/smartos_prompt_config.sh
Allow a bootable `zones` pool, OR if manual pool configuration generates a `standalone` pool, use that.  Bootable pools can be on either BIOS or UEFI.
This is a WIP.  As indicated in the installer comments, the initial thought is to have PIs live in $BOOTPOOL`/boot/platform-YYYYxxxxx/` directories, and have $BOOTPOOL`/boot/platform` symlink to the desired PI.
Needs lots more work, including better install-time mechanisms, and a tool not unlike `sdcadm platform` to deal with PIs.  (One thought I had was `piadm`(1M), which future `sdcadm platform` could use on the Head Node.)
=> OS-8198 Allow bootable-off-ZFS-pool ("standalone") SmartOS

man/usr/share/man/man1m/piadm.1m.md, src/piadm.sh
Subject says it all.  Tested on my `smartos-bios` VM both stock (which produces a lot of output) and with a PIADM_URL_PREFIX that triggers the warning path.
=> OS-8204 Add "avail" subcommand to piadm(1M)

src/piadm.sh
Tested thus far on a SmartOS VM with an EFI-capable `zones` pool using `bootable -d` and then checking the ESP to see that it's erased.
=> OS-8205 `piadm bootable -d` needs to be more thorough

src/piadm.sh
There *should* be no difference in behavior, except for the elimination of various undefined or bug behaviors.
That being said, there's a lot changing here so we'll want to test it against all of our known use cases.
=> OS-8230 want piadm.sh to be shellcheck clean

man/usr/share/man/man1m/piadm.1m.md, src/piadm.sh
After this change piadm will try to symlink `loader.conf.local` and `loader.rc.local` on the install action.
The symlinking is only done when:
- installing boot bits
- either loader.conf.local or loader.rc.local exist in /BOOTFS/common/
This should make it easier for people to load for example a custom ppt_matches and ppt_aliases file.
Testing I've done:
- build a new pi with this applied
- install pi and boot it
- create /standalone/boot/common
- copy my ppt_aliases, ppt_matches, sd.conf, ... to the common directory (mirroring the final location)
- copy my existing loader.conf.local (and modified the paths) to common directory
- create test loader.rc.local that swaps bg and foreground colors
- build a new pi
- install new pi using `piadm install XXX.iso`
- verified that a relative …
=> OS-8209 piadm should allow injecting loader.*.local

Makefile
=> OS-8250 Create 16gb.img in smartos-live

tools/build_live
Only change needed for OpenSSL 3 is to increase the size of the ramdisk (again).
=> OS-8334 Bring OpenSSL 3 to the platform

Makefile, configure, src/Makefile.defs, tools/build_strap, tools/optimize_jobs
This has been tested to prove that both illumos and other gmake get their jobs reduced to the output of the new optimize_jobs script.
=> OS-8385 smartos-live should be smarter about setting MAX_JOBS and friends

src/vm/man/vmadm.8.md, src/vm/node_modules/VM.js
=> OS-8398 Enabling allow_dhcp_spoofing should remove ip-nospoof

src/img/lib/imgadm.js
The maxBuffer is not suitable for production environments with lot's of snapshots and delegate datasets. Especially when the structure contains lot's of sub-folders.
=> Increase maxBuffer for imgadm zfs listing

configure
=> OS-8404 git pbchk needs py39-expat dependency

src/etc/ssh/sshd_config
This only affects the global zone because base zone images have their own sshd_config.
=> OS-8469 Update default sshd_config to reduce log spam

src/vm/node_modules/VM.js
This should help with some of the most commonly reported reprovision failures. Overall, reprovisioning is extremely stable. There are occasional failures experienced by almost everyone, and there is one reported case where failures are frequent. This should address the vast majority of those cases. This may not (and likely doesn't) address *all* reprovisioning failures, and failures being extremely rare it makes this difficult to accurately represent the degree of change.
But overall, this will hopefully reduce the incidents of reprovision failure experienced by operators.
See [OS-8486][1] for testing notes.
[1]: https://smartos.org/bugview/OS-8486
[OS-8486]: https://mnx.atlassian.net/browse/OS-8486?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cif …
=> OS-8486 Occasional issues when reprovisioning zones

src/disklayout.js
The `mountpoint` property on block devices is now `mountpoints` and is also an array.
If no mountpoints exist, the value is: `[null]`
Also filter out any zvol devices which show up in `lsblk` after a Linux CN has been setup.
See [LINUXCN-26](https://mnx.atlassian.net/browse/LINUXCN-26) for testing notes.
[LINUXCN-26]: https://mnx.atlassian.net/browse/LINUXCN-26?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LINUXCN-26 lsblk output has changed in Debian 12

src/vm/node_modules/VM.js
With this change the refreservation on the zoneroot is now 1MiB smaller than before.
Before this patch:
```
[root@e4-43-4b-86-72-ec (ro-1) ~]# zfs get -r refreservation zones/781a2156-b2db-4b88-9bda-01626c900f30
NAME                                              PROPERTY        VALUE      SOURCE
zones/781a2156-b2db-4b88-9bda-01626c900f30        refreservation  1G         local
zones/781a2156-b2db-4b88-9bda-01626c900f30/disk0  refreservation  11.3G      local
zones/781a2156-b2db-4b88-9bda-01626c900f30/disk1  refreservation  54.9G      local
````
After (new VM with same image and package):
```
[root@e4-43-4b-86-72-ec (ro-1) ~]# zfs get -r refreservation zones/654393de-51ad-4bfd-b718-a58ab67aa383
NAME                                              PROPERTY        VALUE      SOURCE …
```
=> OS-8499: non-flexible_disk bhyve can't set indestructible_zoneroot

src/img/lib/sources/imgapi.js
If an image which has children images is disabled, none of those children images can be imported. I bumped into this on a fresh server that didn’t have `b70d5484-5168-4ecb-8127-0a0c59c1d906` (a Ubuntu 20.04 image) on it yet:
```
[root@24-6e-96-5e-b3-9c (ro-1) ~]# imgadm import b70d5484-5168-4ecb-8127-0a0c59c1d906
Importing b70d5484-5168-4ecb-8127-0a0c59c1d906 (ubuntu-20.04.3@20210930) from "http://...snip..."
Gather image b70d5484-5168-4ecb-8127-0a0c59c1d906 ancestry
Uncaught TypeError: Cannot read property 'manifest' of null
FROM
/usr/img/lib/sources/imgapi.js:242:31
/usr/img/lib/sources/imgapi.js:154:9
/usr/img/node_modules/sdc-clients/lib/imgapi.js:698:17
parseResponse (/usr/img/node_modules/restify/lib/clients/json_client.js:84:9)
IncomingMessage.done …
```
=> OS-8501 imgadm will not import active images if they have any inactive origin images

src/vm/node_modules/VM.js
I observed vmadm hanging 60s when performing certain updates. Specifically:
```
[root@00-0c-29-ea-39-bd ~]# time echo '{"internal_metadata_namespaces":["3"]}' | ./vmadm update 3ea41436-8bd6-4225-b415-33c6cd35faab
first of 1 error: vminfod watchForChanges "VM.js update (3ea41436-8bd6-4225-b415-33c6cd35faab)" timeout exceeded
real    1m0.273s
user    0m0.211s
sys     0m0.117s
```
This patch fixes the above problem.
Interestingly, for this bug the update does successfully occur (e.g. `internal_metadata_namespaces` is updated through `zonecfg`), but `vmadm` simply does not terminate for 60s. Also, this hang only occurs for some fields, not others (e.g. `internal_metadata` or `autoboot` both terminate as expected).
After digging a bit, this is happening due to a problem with comparisons: …
=> OS-8537 vmadm hangs for 60s and errors when updating internal_metadata_namespaces.

src/piadm.sh
Testing notes are in ticket.  Gonna try a fresh install once I've built an ISO locally.
=> OS-8539 piadm(8) is noisy when /var/piadm/piadm.conf isn't there

src/vm/node_modules/VM.js
A well-known problem with ZFS occurs when RAIDZ is used with 4K disks (rather than the 512b disks that were the norm when RAIDZ was first added): volumes take excessive amounts of space. E.g. if 100GB is used within the volume, the volume itself on disk will be about 200GB. This is particularly relevant for bhyve or KVM zones.
The simplest way around this pathology is increasing the volblocksize. The default volblocksize is 8K; switching to 16K reduces the space overhead to a more manageable 10-60% for most RAIDZ disk layouts (see below). 32K is a possibility too.
This patch checks all vdevs in a pool, and iff all have ashift=12 and a new volume is being created without an explicit volblocksize given will it switch to volblocksize=16K. It is arguably a simplistic patch, since I wanted to …
=> OS-8531 vmadm should create volumes with larger volblocksize on RAIDZ pools with 4K disks

configure
NOTE:  This commit cannot land until https://www.illumos.org/issues/16319 lands and is merged into illumos-joyent.  It's a baby build flag day for us.
=> OS-8552 illumos-joyent should use tools yacc per illumos#16319

man/usr/share/man/man8/piadm.8.md
=> OS-8567 piadm(8)'s documentation of custom cites BOOTPOOL not BOOTFS

README.md
See #1101
- bump the `base-64-lts` image version to `21.4.1`
=> smartos-live#1101 Minimum platform image to build SmartOS is 20220807

src/vm/node_modules/VM.js, src/vmunbundle.c
Seems like a big hammer, and the answer might be to not prematurely create a ZFS dataset.
=> OS-8518 Receiving a BHYVE VM fails due to premature ZFS dataset creation

configure
Once the lex update lands, we need to use it or gcc 14 build will fail:)
=> OS-8586 illumos-joyent should use tools lex per illumos#16873

man/smartdc/man/man1/sdc-factoryreset.1.md, src/smartdc/bin/sdc-factoryreset.sh
The lower-hanging, lesser-impact, change to `sdc-factoryreset` I'd like to make.
=> OS-8578 Add "-s" option to sdc-factoryreset to poweroff CN instead of reboot

src/vm/etc/vmadm.completion, src/vm/man/vmadm.8.md, src/vm/node_modules/proptable.js
https://smartos.org/bugview/OS-8633
We want `vmadm` to be able to create `builder` branded zones.
Depends on tritondatacenter/illumos-joyent#503
=> OS-8633: Want builder brand for RFD 184

src/lib/sdc/config.sh
bash (and ksh) does not accept just any name for variable name.
=> OS-8647 /lib/sdc/config.sh should validate the variable name

Makefile
This popped up on IRC when someone was asking about our tests tarballs.  This will also require a documentation change in illumos-joyent/usr/src/test/smartos-tests/README as well.  Testing notes will be in the ticket shortly, as I did them once already.
=> OS-8655 tests-tar tarball changes owner/permission on ./.

man/usr/share/man/man8/piadm.8.md, src/piadm.sh
The addition of the -S flag (--show-error) in verbose mode could be useful for troubleshooting.
=> OS-8653 PIADM(8) could be more verbose/helpful about curl(1) errors.

src/Makefile, src/etc/dhcp/eventhook, src/manifest
Fixes tritondatacenter/smartos-ui#19
With this change applied:
```
[root@smartos ~]# svcs vmadmd smartos-ui smartos-ui-executor
STATE          STIME    FMRI
online         19:06:31 svc:/system/smartdc/vmadmd:default
online         19:06:31 svc:/system/smartdc/smartos-ui-executor:default
online         19:06:31 svc:/system/smartdc/smartos-ui:default
[root@smartos ~]# dladm create-vnic -l ixgbe0 dhcptest0
[root@smartos ~]# ifconfig dhcptest0 plumb up
[root@smartos ~]# ifconfig dhcptest0 dhcp
[root@smartos ~]# svcs vmadmd smartos-ui smartos-ui-executor
STATE          STIME    FMRI
online         19:08:47 svc:/system/smartdc/smartos-ui-executor:default
online         19:08:47 svc:/system/smartdc/smartos-ui:default
online         19:08:47 svc:/system/smartdc/vmadmd:default
[root@smartos ~]# …
```
=> OS-8690: smartos-ui does not adapt to changed admin interface IP address
